import type { Metadata } from "next";
import { Outfit, Roboto } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-primary" });
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-secondary",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Flux Figma WebDev + DewDes Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
